# Generated by Django 5.1.4 on 2025-01-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About', max_length=200)),
                ('description', models.TextField()),
                ('point_1', models.CharField(blank=True, max_length=200, null=True)),
                ('point_2', models.CharField(blank=True, max_length=200, null=True)),
                ('point_3', models.CharField(blank=True, max_length=200, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('read_more_link', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
