# Generated by Django 5.1.4 on 2025-01-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_alter_about_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text="Bootstrap icon class (e.g., 'bi bi-activity')", max_length=50)),
                ('description', models.TextField()),
                ('delay', models.IntegerField(default=0, help_text='Animation delay in milliseconds')),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(default='About', max_length=200),
        ),
    ]
