# Generated by Django 5.1.4 on 2025-01-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_service_alter_about_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the call to action', max_length=200)),
                ('description', models.TextField(help_text='Description for the call to action')),
                ('button_text', models.CharField(help_text='Text displayed on the button', max_length=100)),
                ('button_link', models.URLField(help_text='URL the button redirects to')),
            ],
        ),
    ]
