# Generated by Django 5.1.4 on 2025-01-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_calltoaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltoaction',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Background image for the CTA section', upload_to='cta_backgrounds/'),
        ),
        migrations.AddField(
            model_name='calltoaction',
            name='clicks',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the CTA has been clicked'),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='button_link',
            field=models.URLField(help_text='URL for the button'),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='button_text',
            field=models.CharField(default='Call To Action', max_length=100),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='description',
            field=models.TextField(help_text='Description for the CTA'),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='title',
            field=models.CharField(help_text='Title for the CTA', max_length=200),
        ),
    ]
