# Generated by Django 5.1.4 on 2025-01-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_calltoaction_background_image_calltoaction_clicks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='features/')),
            ],
        ),
        migrations.RemoveField(
            model_name='calltoaction',
            name='background_image',
        ),
    ]
