# Generated by Django 5.1.4 on 2025-01-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0014_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='created_at',
            new_name='published_date',
        ),
    ]
