# Generated by Django 5.1.4 on 2025-01-08 13:37

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0015_rename_created_at_blog_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=tinymce.models.HTMLField(help_text="Bootstrap icon class (e.g., 'bi bi-activity')", max_length=50),
        ),
    ]
