# Generated by Django 5.1.4 on 2025-01-08 13:41

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0016_alter_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltoaction',
            name='description',
            field=tinymce.models.HTMLField(help_text='Description for the CTA'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(help_text="Bootstrap icon class (e.g., 'bi bi-activity')", max_length=50),
        ),
    ]
