# Generated by Django 5.1.4 on 2025-01-08 13:44

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0017_alter_calltoaction_description_alter_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltoaction',
            name='title',
            field=tinymce.models.HTMLField(help_text='Title for the CTA', max_length=200),
        ),
    ]
