# Generated by Django 5.1.4 on 2025-01-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0018_alter_calltoaction_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltoaction',
            name='description',
            field=models.TextField(help_text='Description for the CTA'),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='title',
            field=models.CharField(help_text='Title for the CTA', max_length=200),
        ),
    ]
